
stages:
  process_data:
    cmd: venv/bin/python src/data/make_dataset.py --input data/01_raw --output data/03_primary --app-filename application_train_history.csv
    deps:
      - src/data/make_dataset.py
      - data/01_raw/application_train_history.csv
      - data/01_raw/bureau.csv
    outs:
      - data/03_primary

  validate_data:
    cmd: venv/bin/python src/data/validate_data.py --input data/03_primary/credit_data_processed.csv
    deps:
      - src/data/validate_data.py
      - data/03_primary/credit_data_processed.csv

  check_drift:
    cmd: venv/bin/python src/monitoring/drift_detection.py --reference data/03_primary/credit_data_processed.csv --current data/03_primary/credit_data_processed.csv
    deps:
      - src/monitoring/drift_detection.py
      - data/03_primary/credit_data_processed.csv
    outs:
      - reports/drift_report.html

  engineer_features:
    cmd: export PYTHONPATH=$PYTHONPATH:$(pwd) && venv/bin/python src/features/build_features.py --input data/03_primary --output data/04_features
    deps:
      - src/features/build_features.py
      - data/03_primary
    outs:
      - data/04_features

  train_model:
    cmd: export PYTHONPATH=$PYTHONPATH:$(pwd) && venv/bin/python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/04_features
    params:
      - models
    outs:
      - models/lightgbm_model.joblib

  benchmark:
    cmd: venv/bin/python src/models/compare_models.py
    deps:
      - src/models/compare_models.py
      - data/04_features
    outs:
      - reports/benchmark_results.csv
      - models/champion_config.json
